Fail workflow if shaders differ from previous release
Add a step to fail the workflow if shaders differ.

diff --git a/.github/workflows/macos-26-arm64-single-precision-using-patcher.yml b/.github/workflows/macos-26-arm64-single-precision-using-patcher.yml
--- a/.github/workflows/macos-26-arm64-single-precision-using-patcher.yml
+++ b/.github/workflows/macos-26-arm64-single-precision-using-patcher.yml
@@ -423,5 +423,11 @@ jobs:
       env:
         GITHUB_TOKEN: ${{ secrets.PAT }}
 
+    - name: Fail if Shaders Differ to force email alert
+      if: env.ZIPFILENAME == 'OpenSpace-minimal-daily-mac-testing.zip'
+      run: |
+        echo "::error::Shaders differ from the previous release!"
+        exit 1
+
       
     
